version: "3.8"

services:
  m37_db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=m37db
      - MYSQL_ROOT_HOST=%
    ports:
      - "4000:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  m37_server:
    image: almtalal/m37_server:latest
    depends_on:
      - m37_db
    ports:
      - "3010:3000"

volumes:
  db_data:
