version: "3.8"

services:
  m37_db:
    env_file:
      - ./.env
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "4000:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  m37_server:
    image: almtalal/m37:v3
    command: sh -c "sleep 20 && bun run start"
    env_file:
      - ./.env
    depends_on:
      m37_db:
        condition: service_healthy
    ports:
      - "3010:3000"
  
volumes:
  db_data:

